# Lootable Corpses config

# Set in minutes how many minutes before corpses are removed
# Set to 0 to not remove corpses automatically
remove-corpse-after-minutes: 2

# Set in minutes how many minutes before corpses are removed after interaction
# Set to 0 to remove instantly after interaction
# Set to -1 to disable
remove-corpse-after-interaction-minutes: 0

# Disable looting corpses
disable-looting: false

# Instant respawn - cancel death screen
instant-respawn: true

# Kill players when leaving game
kill-on-leave: false

# Drop inventory when corpse despawns
drop-inv-on-despawn: true

# Custom inventory title
inventory-title: "{player}'s inventory"

# Set whether the corpse is generated above the Void when a player dies in the Void
keep-corpses-above-the-void: true

# Blacklisted worlds - disable lootable corpses in certain worlds
blacklisted-worlds:
  - world_nether